let shopItemsData = [
  {
    id: "hsgshjd",
    name: "Cuddle Care",
    price: 70,
    img: "img/cart-cream1.jpg",
    details: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
  },
  {
    id: "wqsawqs",
    name: "Berry Sensation",
    price: 90,
    img: "img/cart-cream2.jpg",
    details: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
  },
  {
    id: "asdfjk",
    name: "Beach Butter",
    price: 43,
    img: "img/cart-cream3.jpg",
    details: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
  },
  {
    id: "qwerty",
    name: "Caramel Oil",
    price: 20,
    img: "img/cart-cream4.jpg",
    details: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
  },
  {
    id: "eqtwrtrq",
    name: "Luscious Lotion",
    price: 46,
    img: "img/cart-cream5.jpg",
    details: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
  },
  {
    id: "ppqoaok",
    name: "Minty Sunshine",
    price: 55,
    img: "img/cart-cream6.jpg",
    details: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
  },
  {
    id: "wqssawqs",
    name: "Peach Refresher",
    price: 20,
    img: "img/cart-cream7.jpg",
    details: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
  },
  {
    id: "ppqoiws",
    name: "Blonde Moment",
    price: 65,
    img: "img/cart-cream8.jpg",
    details: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
  },
  {
    id: "oiwueie",
    name: "Magic Belle",
    price: 30,
    img: "img/cart-cream9.jpg",
    details: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
  },
  {
    id: "wqsdats",
    name: "Smooth Radiance",
    price: 20,
    img: "img/cart-cream10.jpg",
    details: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
  },
  {
    id: "rwfaesf",
    name: "Lotion Up",
    price: 50,
    img: "img/cart-cream11.jpg",
    details: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
  },
  {
    id: "pquweue",
    name: "Honey Babe",
    price: 32,
    img: "img/cart-cream12.jpg",
    details: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
  },
  {
    id: "yerywuw",
    name: "Beyond Butter",
    price: 65,
    img: "img/cart-cream13.jpg",
    details: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
  },
  {
    id: "ruatssj",
    name: "Sun Burst",
    price: 45,
    img: "img/cart-cream14.jpg",
    details: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
  },
  {
    id: "soisud",
    name: "Dandelion Dream",
    price: 30,
    img: "img/cart-cream15.jpg",
    details: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
  },
  {
    id: "yehhejd",
    name: "Lavish Lavender",
    price: 25,
    img: "img/cart-cream16.jpg",
    details: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
  },
  {
    id: "trsysygs",
    name: "Exotic Oasis",
    price: 20,
    img: "img/cart-cream17.jpg",
    details: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
  },
];
